fos_rest:
  param_fetcher_listener: force
  format_listener:
    rules:
        - { path: ^/api, priorities: [ 'json', 'html', '*/*' ], fallback_format: json, prefer_extension: true }
        - { path: ^/, priorities: [ 'html', '*/*' ], fallback_format: html, prefer_extension: true }
